# Generated by Django 2.2.5 on 2019-10-02 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordscounter',
            name='file',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='WordsCounter',
        ),
    ]
